# Generated by Django 5.1.1 on 2024-10-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('format', models.CharField(default='png', max_length=16)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('format', models.CharField(default='mp4', max_length=16)),
                ('duration', models.FloatField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('bit_rate', models.IntegerField(null=True)),
                ('frame_rate', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
