# Generated by Django 5.1.1 on 2024-10-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationmessage',
            options={'ordering': ('created_at',)},
        ),
    ]
