# Generated by Django 5.1.1 on 2024-10-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_trend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattachment',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
