# Generated by Django 5.1.1 on 2024-10-07 15:00
<<<<<<< HEAD
# Generated by Django 5.1.1 on 2024-10-07 14:55
=======
>>>>>>> feature/notification

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_avatar'),
        ('account', '0002_user_posts_count'),
    ]

    operations = [
    ]
