<<<<<<< HEAD
# Generated by Django 5.1.1 on 2024-10-07 15:00
=======
# Generated by Django 5.1.1 on 2024-10-07 14:55
>>>>>>> 4bddc1161a5398f5e73e8e4faa0df77adf537c53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_avatar'),
        ('account', '0002_user_posts_count'),
    ]

    operations = [
    ]
